const routes = {
    home: '/',
    admin: '/admin/chart',
    recruiter: '/recruiter/recruiterpost',
    recruitersaved: '/recruiter/savedpost',
    profile: '/profile',
    settings: '/settings',
    accounts: '/accounts',
    blog: '/blog/post',
    cv: '/cv',
    recruitment: '/recruitmentpage',
    testuser: '/testuser',
    informationtechnology: '/testuser/informationtechnology',
    marketing: '/testuser/marketing',
    businessadministration: '/testuser/businessadministration',
    linguistics: '/testuser/linguistics',
    postquiz: '/postquiz',
    recruiterpost: '/recruiter/recruiterpostjob',
    recruitmentdetail: '/recruitmentdetail',
    recruitmentpage: '/recruitmentpage/user',
    displayquizz: 'testuser/displayquizz',
    savepost: '/blog/savedPost',
    usersManagement: '/admin/usermanagement',
    editPost: '/recruiter/recruiterpostjob/:id',
    blogpost: '/blog/postblog',
};

export default routes;
